celery_l/optimaze/mailsender/urls.py
from django.urls import path
from .views import send_email, answer_page_view


app_name = 'mailsender'

urlpatterns = [
    path('', send_email, name='send_email'),
    path('answer/', answer_page_view, name='answer_page'),
]

celery_l/optimaze/optimaze/urls.py
from typing import Any
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns: list[Any] = [
    path('admin/', admin.site.urls),
    path('', include('mailsender.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns + = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

celery_l/optimaze/mailsender/models.py
from django.db import models

# Create your models here.

celery_l/optimaze/mailsender/forms.py
from django import forms
import re


class EmailForm(forms.Form):
    subject = forms.CharField(label='Enter subject')
    sender = forms.EmailField(label='Enter email to send')
    message = forms.CharField()

    def clean_sender(self):
        sender = self.cleaned_data['sender']
        pattern = r'^[a-zA-Z0-9._%+-]+@gmail\.com$'
        if not re.match(pattern, sender):
            raise forms.ValidationError('You must enter a valid email address')
        return sender

celery_l/optimaze/mailsender/views.py
from django.shortcuts import render, redirect, reverse
from .forms import EmailForm
from django.conf import settings
from django.core.mail import send_mail


def send_email(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            to_send = [
                form.cleaned_data['sender'],
            ]
            from_email = settings.EMAIL_HOST_USER

            send_mail(subject, message, from_email, to_send)
            request.session['recipient_list'] = to_send
            return redirect(reverse('mailsender:answer_page'))
    else:
        form = EmailForm()

    return render(request, 'mailsender/email.html', {'form': form})


def answer_page_view(request):
    return render(request, 'mailsender/answer/success.html', {
        'recipient_list': request.session.get('recipient_list', []),
    })

celery_l/optimaze/mailsender/templates/mailsender/answer/success.html
{% extends 'mailsender/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card mt-5">
                    <div class="card-body">
                        <p class="mb-4">Your email has been sent successfully to </p>
                        {% if recipient_list %}
                            {% for recipient in recipient_list %}
                                <p>{{ recipient }}</p>
                            {% endfor %}
                        {% endif %}
                        <a href="{% url 'mailsender:send_email' %}" class="back_url">Back to Send Email</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

celery_l/optimaze/mailsender/templates/mailsender/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Send Email</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">-->

</head>
<body>

<div class="navbar">
    <a href="{% url 'mailsender:send_email' %} ">Home</a>
    <a href="#">About</a>
    <a href="#">Contact</a>
</div>
    {% block content %}  {% endblock %}


<!--    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>-->
</body>
</html>

celery_l/optimaze/mailsender/templates/mailsender/email.html
{% extends  'mailsender/base.html' %}
 {% block content %}
    <div class="container">
        <h2>Send Email</h2>

        <form action="{% url 'mailsender:send_email' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Send Email</button>
        </form>
    </div>
{% endblock %}